In [1]:
import numpy as np
a1 = np.array([1,2,3,4,5,6])
a2 = np.array([
    [1,2],
    [3,4],
    [5,6],
])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [4]:
#Shapes
print("Shape of a1: "+str(a1.shape))
print("Shape of a2: "+str(a2.shape))
print("Shape of a3: "+str(a3.shape))

Shape of a1: (6,)
Shape of a2: (3, 2)
Shape of a3: (2, 3, 3)


In [5]:
#Number of Dimension
print("Number of Dimension of a1: "+str(a1.ndim))
print("Number of Dimension of a2: "+str(a2.ndim))
print("Number of Dimension of a3: "+str(a3.ndim))

Number of Dimension of a1: 1
Number of Dimension of a2: 2
Number of Dimension of a3: 3


In [6]:
#Data types
print("Data Type of a1: "+str(a1.dtype))
print("Data Type of a2: "+str(a2.dtype))
print("Data Type of a3: "+str(a3.dtype))

Data Type of a1: int32
Data Type of a2: int32
Data Type of a3: int32


In [7]:
#Size
print("Size of a1: "+str(a1.size))
print("Size of a2: "+str(a2.size))
print("Size of a3: "+str(a3.size))

Size of a1: 6
Size of a2: 6
Size of a3: 18


In [10]:
#Type
print("Type of a1: "+str(type(a1)))
print("Type of a2: "+str(type(a2)))
print("Type of a3: "+str(type(a3)))

Type of a1: <class 'numpy.ndarray'>
Type of a2: <class 'numpy.ndarray'>
Type of a3: <class 'numpy.ndarray'>


In [12]:
import pandas as pd
df = pd.DataFrame(a2)
df

0  1
0  1  2
1  3  4
2  5  6

In [15]:
ones = np.ones(shape=(10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
zeros = np.zeros(shape = (7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
ranged = np.arange(0,100,3)
ranged

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [21]:
r_int = np.random.randint(0,10, size=(7, 2))
r_int

array([[9, 5],
       [1, 8],
       [5, 9],
       [6, 8],
       [3, 8],
       [4, 2],
       [8, 9]])

In [25]:
r_float = np.random.random((3,5))
r_float

array([[0.53932394, 0.28204575, 0.32281491, 0.29856457, 0.43678671],
       [0.10540439, 0.48400699, 0.70931952, 0.18029567, 0.47215315],
       [0.81407156, 0.66003698, 0.00409792, 0.34997696, 0.98732328]])

In [28]:
np.random.seed(42)
r1 = np.random.randint(10, size=(4,6))
r1

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [31]:
r2 = np.random.randint(1,10, size=(3, 7))
r2, np.unique(r2)

(array([[2, 5, 8, 9, 9, 1, 9],
        [7, 9, 8, 1, 8, 8, 3],
        [1, 8, 3, 3, 1, 5, 7]]),
 array([1, 2, 3, 5, 7, 8, 9]))

In [32]:
r2[0]

array([2, 5, 8, 9, 9, 1, 9])

In [36]:
r2[:2,:2]

array([[2, 5],
       [7, 9]])

In [38]:
r3 = np.random.randint(10, size=(3, 5))
r4 = np.ones(shape = (3, 5))
r3 + r4

array([[ 1.,  3.,  5.,  3.,  1.],
       [ 5., 10.,  7.,  7.,  9.],
       [10., 10.,  3.,  7.,  1.]])

In [39]:
r5 = np.ones(shape = (5, 3))
r5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
r5 + r4

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [52]:
r6 = np.ones(shape=(3, 5))
r6 - r3

array([[ 1., -1., -3., -1.,  1.],
       [-3., -8., -5., -5., -7.],
       [-8., -8., -1., -5.,  1.]])

In [53]:
r6 * r3

array([[0., 2., 4., 2., 0.],
       [4., 9., 6., 6., 8.],
       [9., 9., 2., 6., 0.]])

In [54]:
r3 ** 2, np.square(r6)

(array([[ 0,  4, 16,  4,  0],
        [16, 81, 36, 36, 64],
        [81, 81,  4, 36,  0]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [55]:
np.mean(r3)

4.466666666666667

In [56]:
np.max(r3)

9

In [57]:
np.min(r3)

0

In [58]:
np.std(r3)

3.263263533472111

In [59]:
np.var(r3)

10.648888888888889

In [63]:
r7 = r6.reshape((3, 5, 1))
r7

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [64]:
r7.transpose()

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [69]:
arr1 = np.random.randint(10, size=(3, 3))
arr2 = np.random.randint(10, size=(3, 2))
np.dot(arr1,arr2)

[[30 64]
 [52 68]
 [58 63]]


In [70]:
arr3 = np.random.randint(10, size=(4,3))
arr4 = np.random.randint(10, size=(4,3))
np.dot(arr3, arr4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [74]:

np.dot(arr3.T, arr4)


array([[ 49,  87,  72],
       [ 18,  44,  14],
       [ 81, 132,  85]])

In [77]:
arr5 = np.random.randint(10, size=(2,7))
arr6 = np.random.randint(10, size=(2,7))
arr5,arr6, arr5 > arr6, arr5 >= arr6

(array([[5, 5, 5, 2, 5, 7, 1],
        [4, 0, 0, 4, 2, 3, 2]]),
 array([[0, 0, 4, 5, 2, 8, 4],
        [7, 0, 4, 2, 0, 3, 4]]),
 array([[ True,  True,  True, False,  True, False, False],
        [False, False, False,  True,  True, False, False]]),
 array([[ True,  True,  True, False,  True, False, False],
        [False,  True, False,  True,  True,  True, False]]))

In [78]:
arr5 > 7

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [79]:
arr5 == arr6

array([[False, False, False, False, False, False, False],
       [False,  True, False, False, False,  True, False]])

In [85]:
np.sort(arr5), np.argsort(arr5)

(array([[1, 2, 5, 5, 5, 5, 7],
        [0, 0, 2, 2, 3, 4, 4]]),
 array([[6, 3, 0, 1, 2, 4, 5],
        [1, 2, 4, 6, 5, 0, 3]], dtype=int64))

In [87]:
np.argmax(arr5), np.argmin(arr5)

(5, 8)

In [89]:
np.argmax(arr5,axis=1), np.argmin(arr5,axis=0)

(array([5, 0], dtype=int64), array([1, 1, 1, 0, 1, 1, 0], dtype=int64))

In [90]:
np.random.randn(4, 3)

array([[-0.60937338, -0.8135211 , -2.31806825],
       [-0.26801835,  1.09632979, -0.33541102],
       [ 0.63511255, -1.08020087, -1.30569755],
       [-0.75076184, -1.02549987, -1.18303961]])

In [91]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])